[package]
name = "quick-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["quickjs-sys"]

[dependencies]
quickjs-sys = { path = "quickjs-sys" }
thiserror = { version = "1", default-features = false }
anyhow = { version = "1", default-features = false }
log = { version = "0.4", default-features = false }
reqwest = { version = "0.11", features = [
    "blocking",
    "rustls-tls-webpki-roots",
], default-features = false }
once_cell = { version = "1", features = ["std"], default-features = false }
image = { version = "0.24", features = ["ico"], default-features = false }
imageproc = { version = "0.23", default-features = false }
image_hasher = { version = "1", default-features = false }
fast_qr = { version = "0.10", features = ["image"], default-features = false }
barcoders = { version = "1", features = ["image"], default-features = false }
plotters = { git = "https://github.com/plotters-rs/plotters.git", features = ["bitmap_backend","bitmap_encoder","ab_glyph"], default-features = false }

